# 项目端口
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  redis:
    password: ${REDIS_PASSWORD}
logging:
  level:
    root: warn
    com:
      wulizhou:
        pets:
          model:
            mapper: warn
  file: /app/pets.log